/* Development-only browser regression. Serve the repository with a static HTTP server. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.TEST_URL||'http://127.0.0.1:8765/index.html',output=process.env.TEST_OUTPUT||path.resolve('guardian-test-results');
fs.mkdirSync(output,{recursive:true});const evidence=[];
async function layout(p,label){const r=await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,over:[...document.querySelectorAll('main button,main p,main h1,main h2,main select,.bottom,.health-panel,.answer,.answer-dialog,.answer-scroll,.stage-notice')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&(r.left< -1||r.right>innerWidth+1)}).map(e=>e.id||e.className),small:[...document.querySelectorAll('button,select,summary,a.button-link')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&!e.disabled&&(r.height<43||r.width<43)}).map(e=>e.id||e.className)}));assert(r.scroll<=r.width,`${label} overflow ${JSON.stringify(r)}`);assert.deepEqual(r.over,[],label);assert.deepEqual(r.small,[],label+' touch');}
async function shot(p,name,fullPage=false){await p.screenshot({path:path.join(output,name+'.png'),fullPage,animations:'disabled'});}
async function setup(browser,w=430,h=932){const ctx=await browser.newContext({viewport:{width:w,height:h},isMobile:true,hasTouch:true,reducedMotion:'reduce'}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await p.goto(base);const data=await p.evaluate(()=>window.ImmuneGuardianData);return {ctx,p,errors,data};}
function baseDamage(n){return n>=70?32:n>=60?30:n>=50?28:n>=40?26:n>=30?24:n>=20?22:n>=10?20:n>=6?18:n>=4?15:n>=2?12:10;}
async function answer(p,data,ok=true){const prompt=await p.locator('#question').innerText();const current=data.national.concat(data.concept).find(q=>q.q===prompt);assert(current,'question belongs to original bank');const wanted=ok?current.ans:current.options.find(o=>o!==current.ans);await p.locator('.option').filter({has:p.getByText(wanted,{exact:true})}).click();assert.match(await p.locator('#answer').innerText(),ok?/✓ 答對/:/✕ 答錯/);assert.match(await p.locator('#answer').innerText(),/正確答案/);assert.match(await p.locator('#answer').innerText(),/為什麼/);assert.equal(await p.locator('.option:not(:disabled)').count(),0);return current;}
async function advance(p){await p.locator('#continueBattleBtn').click();assert(!(await p.locator('#answerDialog').isVisible()));}
async function perfect(browser,name,w,h,mode='all'){
 const {ctx,p,errors,data}=await setup(browser,w,h);const total=mode==='all'?70:mode==='national'?20:50;
 assert.equal(data.national.length,20);assert.equal(data.concept.length,50);assert.equal(data.stages.length,5);const bank=data.national.concat(data.concept);assert.equal(new Set(bank.map(q=>q.id)).size,70);for(const q of bank){assert.equal(q.options.length,4);assert.equal(new Set(q.options).size,4);assert(q.options.includes(q.ans));assert(q.exp&&q.src);}
 await layout(p,'lobby');if(mode==='all')await shot(p,`${name}-${w}-home`);assert(!(await p.locator('#battleActions').isVisible()));await p.locator('#gameMode').selectOption(mode);await p.locator('#startBtn').click();assert(await p.locator('#nextBtn').isDisabled());assert(await p.locator('#answerBtn').isDisabled());await layout(p,'battle');if(mode==='all')await shot(p,`${name}-${w}-battle`);
 const seen=new Set(),forms=new Set();let score=0;const plan=data.stages.map((_,i)=>{let hp=0;for(let q=Math.floor(i*total/5)+1;q<=Math.floor((i+1)*total/5);q++)hp+=Math.max(5,Math.round(baseDamage(q)*(1-i*.1)));return hp});
 for(let i=1;i<=total;i++){
  const stage=Math.ceil(i/(total/5));assert.equal(await p.locator('#stageBadge').innerText(),`${stage} / 5`);assert.equal(await p.locator('#progress').innerText(),`第 ${i} / ${total} 題`);await layout(p,'question '+i);const sceneBox=await p.locator('#battle').boundingBox(),questionBox=await p.locator('#question').boundingBox(),controls=await p.locator('#battleActions').boundingBox();assert(sceneBox.y>=0&&sceneBox.y+sceneBox.height<questionBox.y,'scene above question');assert(questionBox.y+questionBox.height<controls.y,'whole question visible with scene');
  const question=await answer(p,data);assert(!seen.has(question.id));seen.add(question.id);score+=baseDamage(i);assert.equal(await p.locator('#streak').innerText(),String(i));assert.equal(await p.locator('#score').innerText(),String(score));assert.equal(await p.locator('#hp').innerText(),'7');forms.add(await p.locator('#bossFormLabel').textContent());
  const health=Number(await p.locator('#enemyMeter').getAttribute('aria-valuenow'));assert(health>=0&&health<=plan[stage-1]);assert.equal(Number(await p.locator('#enemyMeter').getAttribute('aria-valuemax')),plan[stage-1]);
  const expectedKills=Math.floor(i/(total/5));assert.equal(await p.locator('#defeated').innerText(),`${expectedKills} / 5`);await layout(p,'feedback '+i);
  if(i===1&&mode==='all')await shot(p,`${name}-${w}-feedback`);
  // Even repeated programmatic answer events cannot award damage/score twice.
  if(i===1){await p.locator('.option.correct').dispatchEvent('click');assert.equal(await p.locator('#score').innerText(),String(score));}
  await advance(p);
 }
 assert.match(await p.locator('#resultTitle').innerText(),/FINAL CLEAR/);assert.match(await p.locator('#result').innerText(),new RegExp(`${total}/${total} 題已作答`));assert.match(await p.locator('#result').innerText(),/5\/5/);assert.equal(seen.size,total);await layout(p,'result');if(mode==='all'){assert(forms.has('終極型態'));await shot(p,`${name}-${w}-result`,true);}
 // Return goes directly to existing diagnosis, and this game never writes student data.
 assert.equal(await p.evaluate(()=>localStorage.getItem('immuneRushSave')),null);
 await p.locator('#returnMission').click();assert(await p.locator('#reportView').isVisible());assert.equal(await p.locator('#xpTop').innerText(),'0');
 assert.deepEqual(errors,[]);await ctx.close();evidence.push({engine:name,width:w,height:h,mode,total,allFiveBosses:'PASS',result:'PASS'});console.log(`PASS ${name} ${w} ${mode} ${total} questions`);
}
async function edges(browser,name){
 const {ctx,p,errors,data}=await setup(browser);await p.evaluate(()=>localStorage.setItem('immuneRushSave',JSON.stringify({version:2,xp:250,scores:{defense:80},unlocked:2})));const saved=await p.evaluate(()=>localStorage.getItem('immuneRushSave'));
 await p.locator('#startBtn').click();await p.locator('#nextBtn').dispatchEvent('click');assert.equal(await p.locator('#progress').innerText(),'第 1 / 70 題');
 await answer(p,data,false);await p.waitForTimeout(2700);assert.equal(await p.locator('#progress').innerText(),'第 1 / 70 題');assert(await p.locator('#answer').isVisible());assert.equal(await p.locator('#hp').innerText(),'6');
 // The modal scrolls internally; its continue action remains inside the viewport.
 await p.locator('#answer .source summary').click();await p.locator('#answerScroll').evaluate(e=>e.scrollTop=e.scrollHeight);const ar=await p.locator('#answerDialog').boundingBox(),fr=await p.locator('#continueBattleBtn').boundingBox();assert(ar.y>=0&&ar.y+ar.height<=932&&fr.y+fr.height<=932);
 const progress=await p.locator('#progress').innerText(),scoreBefore=await p.locator('#score').innerText();await p.locator('#closeAnswerBtn').click();assert(!(await p.locator('#answerDialog').isVisible()));await p.locator('#answerBtn').click();assert.equal(await p.locator('#progress').innerText(),progress);assert.equal(await p.locator('#score').innerText(),scoreBefore);await p.keyboard.press('Escape');assert(!(await p.locator('#answerDialog').isVisible()));await p.locator('#answerBtn').click();
 await shot(p,`${name}-wrong-feedback`);for(let i=1;i<7;i++){await advance(p);await answer(p,data,false);}assert.equal(await p.locator('#hp').innerText(),'0');assert(await p.locator('#answer').isVisible());await advance(p);assert.match(await p.locator('#resultTitle').innerText(),/生命歸零/);assert.equal(await p.locator('.review-item').count(),7);await p.locator('.review-item summary').first().click();assert.match(await p.locator('.review-item').first().innerText(),/正確答案/);await layout(p,'wrong review');
 await p.locator('#retryBtn').click();assert.equal(await p.locator('#hp').innerText(),'7');assert.equal(await p.locator('#streak').innerText(),'0');assert.equal(await p.locator('#score').innerText(),'0');assert.equal(await p.locator('#progress').innerText(),'第 1 / 70 題');
 p.once('dialog',d=>d.dismiss());await p.locator('#endBtn').click();assert(await p.locator('#playArea').isVisible());p.once('dialog',d=>d.accept());await p.locator('#endBtn').click();assert.match(await p.locator('#resultTitle').innerText(),/已結束/);await p.locator('#changeModeBtn').click();assert(await p.locator('#lobby').isVisible());assert(!(await p.locator('#battleActions').isVisible()));
 await p.locator('#gameMode').selectOption('national');await p.locator('#startBtn').click();for(let i=1;i<=20;i++){await answer(p,data,i!==1);await advance(p);}assert.match(await p.locator('#resultTitle').innerText(),/本輪題目完成/);
 // Counter damage rises at stages 3 and 5, with safe zero clamp.
 await p.locator('#retryBtn').click();for(let i=1;i<=8;i++){await answer(p,data);await advance(p);}assert.equal(await p.locator('#stageBadge').innerText(),'3 / 5');await answer(p,data,false);assert.equal(await p.locator('#hp').innerText(),'5');
 await p.locator('#closeAnswerBtn').click();p.once('dialog',d=>d.accept());await p.locator('#endBtn').click();await p.locator('#retryBtn').click();for(let i=1;i<=16;i++){await answer(p,data);await advance(p);}assert.equal(await p.locator('#stageBadge').innerText(),'5 / 5');await answer(p,data,false);assert.equal(await p.locator('#hp').innerText(),'4');await advance(p);await answer(p,data,false);assert.equal(await p.locator('#hp').innerText(),'1');await advance(p);await answer(p,data,false);assert.equal(await p.locator('#hp').innerText(),'0');await advance(p);assert.match(await p.locator('#resultTitle').innerText(),/生命歸零/);
 assert.equal(await p.evaluate(()=>localStorage.getItem('immuneRushSave')),saved);
 // Text reflow and keyboard: 200% at the narrowest target size.
 await p.locator('#changeModeBtn').click();await p.setViewportSize({width:375,height:812});await p.addStyleTag({content:'html{font-size:32px}'});await layout(p,'200 percent lobby');await p.locator('#startBtn').focus();await p.keyboard.press('Enter');await layout(p,'200 percent battle');await p.locator('.option').first().focus();await p.keyboard.press('Enter');await layout(p,'200 percent feedback');assert(await p.locator('#answer').isVisible());
 assert.deepEqual(errors,[]);await ctx.close();evidence.push({engine:name,edgeCases:'blocked skips, exactly-once scoring, manual explanation, life zero, reset/retry, stop confirmation, pool exhaustion, stage counter damage, isolated storage, 200% text, keyboard',result:'PASS'});console.log(`PASS ${name} edge cases`);
}
(async()=>{for(const name of (process.env.TEST_ENGINES||'chromium,webkit').split(',')){const browser=await(name==='chromium'?chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})}):webkit.launch({headless:true}));try{for(const [w,h] of [[430,932],[390,844],[375,812]])await perfect(browser,name,w,h);for(const mode of ['national','concept'])await perfect(browser,name,430,932,mode);await edges(browser,name);}finally{await browser.close();}}fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({testedAt:new Date().toISOString(),url:base,evidence},null,2));console.log('ALL PASS');})().catch(e=>{fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({evidence,error:String(e.stack)},null,2));console.error(e);process.exit(1)});
