let questions=[],explanations={},session=[],pos=0,answers=[],mode='quick',tick=null,advanceTick=null,seconds=0;
const $=s=>document.querySelector(s), store=JSON.parse(localStorage.getItem('aiapProgress')||'{"history":{},"marked":[]}');
const save=()=>localStorage.setItem('aiapProgress',JSON.stringify(store));
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const normalizeKey=s=>(s||'').normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');
const getExplanation=q=>explanations[normalizeKey(q.question)]||'';
function home(){clearInterval(tick);clearTimeout(advanceTick);$('#quiz').hidden=true;$('#result').hidden=true;$('#home').hidden=false;$('#timer').textContent='';updateStats()}
function pool(){let b=+$(`#bank`).value;return questions.filter(q=>!b||q.bank===b)}
function start(m,custom,startAt){clearInterval(tick);clearTimeout(advanceTick);$('#timer').textContent='';if(m==='continue'){m='all';startAt=store.allPosition||1}mode=m;let p=pool(),n=10,title='10 題快速練習';if(m==='sprint'){n=20;title='考前衝刺 20 題';p=[...shuffle(p.filter(q=>store.history[q.id]?.last===false)),...shuffle(p.filter(q=>!store.history[q.id])),...shuffle(p.filter(q=>store.history[q.id]?.last===true))]}else if(m==='mock'){n=50;title='50 題計時模考';seconds=45*60;$('#timer').textContent='45:00';tick=setInterval(timer,1000)}else if(m==='wrong'){p=p.filter(q=>store.history[q.id]?.last===false);n=p.length;title='錯題重練'}else if(m==='all'){p=questions.slice(Math.max(0,(startAt||1)-1));n=p.length;title=startAt>1?`完整題庫｜從第 ${startAt} 題`:'完整題庫'}if(custom){p=custom;n=p.length;title='本次錯題重練'}if(!n)return alert('目前沒有可重練的錯題，先去刷幾題吧！');session=m==='all'?[...p]:p.slice(0,n);if(!custom&&m!=='sprint'&&m!=='all')session=shuffle(p).slice(0,n);pos=0;answers=[];$('#modeTitle').textContent=title;$('#home').hidden=true;$('#result').hidden=true;$('#quiz').hidden=false;render()}
function render(){let q=session[pos],mock=mode==='mock';if(mode==='all'){store.allPosition=q.id;save()}$('#counter').textContent=mode==='all'?`完整第 ${q.id} / 200 題`:`第 ${pos+1} / ${session.length} 題`;$('#bar').style.width=`${mode==='all'?(q.id-1)/2:pos/session.length*100}%`;$('#qmeta').textContent=`題庫 ${q.bank}｜原題第 ${q.number} 題｜完整編號 ${q.id}`;$('#question').textContent=q.question;$('#choices').innerHTML=Object.entries(q.choices).map(([k,v])=>`<button data-k="${k}"><i>${k}</i><span>${v}</span></button>`).join('');let f=$('#feedback');f.hidden=true;f.className='';f.replaceChildren();$('#next').disabled=true;$('#next').textContent=pos===session.length-1?'完成練習':'下一題 →';$('#mark').classList.toggle('active',store.marked.includes(q.id));$('#mark').textContent=store.marked.includes(q.id)?'★ 已標記':'☆ 不確定';$('#choices').querySelectorAll('button').forEach(b=>b.onclick=()=>choose(b.dataset.k,mock))}
function advance(){clearTimeout(advanceTick);if(pos++<session.length-1)render();else finish()}
function showFeedback(q,ok){let f=$('#feedback');f.hidden=false;f.className=ok?'good':'bad';f.replaceChildren();let title=document.createElement('div');title.className='feedback-title';title.textContent=ok?'✓ 答對了！':`✕ 答錯了，正確答案是 ${q.answer}`;f.appendChild(title);let box=document.createElement('div');box.className='explanation';let label=document.createElement('span');label.className='ex-label';label.textContent='詳解｜';box.append(label,document.createTextNode(getExplanation(q)||'本題詳解尚未成功載入，請重新整理頁面。'));f.appendChild(box)}
function choose(k,mock){if(answers[pos])return;let q=session[pos],ok=k===q.answer;answers[pos]={pick:k,ok};store.history[q.id]={last:ok,seen:(store.history[q.id]?.seen||0)+1};save();document.querySelectorAll('.choices button').forEach(b=>{b.disabled=true;if(mock)b.classList.toggle('selected',b.dataset.k===k);else{if(b.dataset.k===q.answer)b.classList.add('right');if(b.dataset.k===k&&!ok)b.classList.add('wrong')}});if(!mock)showFeedback(q,ok);$('#next').disabled=false;if(mock)advanceTick=setTimeout(advance,350)}
function finish(){clearInterval(tick);clearTimeout(advanceTick);$('#quiz').hidden=true;$('#result').hidden=false;$('#timer').textContent='';let good=answers.filter(a=>a.ok).length,pct=Math.round(good/session.length*100);$('#score').textContent=`${pct} 分`;$('#resultTitle').textContent=pct>=80?'狀態很好，繼續保持！':pct>=60?'已經上手，再補強錯題':'先抓核心觀念，分數會很快上來';$('#resultText').textContent=`答對 ${good} 題，共 ${session.length} 題；本次錯 ${session.length-good} 題。`;$('#retry').hidden=good===session.length;$('#retry').onclick=()=>start('retry',session.filter((_,i)=>!answers[i].ok));updateStats()}
function updateStats(){let h=Object.values(store.history),good=h.filter(x=>x.last).length,wrong=h.filter(x=>!x.last).length,pct=h.length?Math.round(good/h.length*100):0;$('#done').textContent=h.length;$('#correct').textContent=`${pct}%`;$('#wrong').textContent=wrong;$('#mastery').textContent=questions.length?`${Math.round(good/questions.length*100)}%`:'0%';$('#wrongHint').textContent=wrong?`${wrong} 題等待雪恥`:'目前沒有錯題';let c=store.allPosition>1&&store.allPosition<=200;$('#continueBtn').hidden=!c;if(c)$('#continueTitle').textContent=`繼續完整第 ${store.allPosition} 題`}
function timer(){seconds--;let m=Math.floor(seconds/60),s=seconds%60;$('#timer').textContent=`${m}:${String(s).padStart(2,'0')}`;if(seconds<=0){while(answers.length<session.length)answers.push({pick:null,ok:false});finish()}}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>start(b.dataset.mode));$('#jumpBtn').onclick=()=>{let n=Number($('#jumpNo').value);if(!Number.isInteger(n)||n<1||n>200)return alert('請輸入 1–200 的題號');start('all',null,n)};$('#jumpNo').onkeydown=e=>{if(e.key==='Enter')$('#jumpBtn').click()};$('#next').onclick=advance;$('#back').onclick=home;$('#goHome').onclick=home;$('#mark').onclick=()=>{let id=session[pos].id,i=store.marked.indexOf(id);i<0?store.marked.push(id):store.marked.splice(i,1);save();render()};$('#reset').onclick=()=>{if(confirm('確定清除所有作答與錯題紀錄？')){localStorage.removeItem('aiapProgress');location.reload()}};
Promise.all([fetch('data/questions.json').then(r=>r.json()),...[1,2,3,4].map(i=>fetch(`data/explanations-${i}.json?v=1`).then(r=>r.json()))]).then(([q,...parts])=>{questions=q;explanations=Object.assign({},...parts);let missing=questions.filter(x=>!getExplanation(x));if(missing.length)console.warn(`有 ${missing.length} 題詳解尚未對應`,missing.map(x=>x.id));updateStats()}).catch(err=>{console.error(err);alert('題庫載入失敗，請重新整理頁面。')});
